#ifndef SOURCE_PDS_COMMAND_CONTRACT_H
#define SOURCE_PDS_COMMAND_CONTRACT_H

#include <stdint.h>

#define ESP32_UART_RX_PIN 16
#define ESP32_UART_TX_PIN 17
#define USB_SERIAL_BAUD 115200
#define SAMD21_UART_BAUD 115200

#define PDS_BOARD_COMMAND_OFF 0x30u
#define PDS_BOARD_COMMAND_RUN_PWM 0x31u
#define PDS_BOARD_COMMAND_START_MPPT_DEMO 0x32u
#define PDS_BOARD_COMMAND_START_STATE_DEMO 0x33u
#define PDS_BOARD_COMMAND_INJECT_STATE_INPUTS 0x34u
#define PDS_BOARD_COMMAND_GET_VALUES 0x35u
#define PDS_BOARD_COMMAND_STREAM_VALUES 0x36u

#define PDS_CURVE_TYPE_QUADRATIC 0u

#define PDS_VALUE_FIELD_MODE (1ul << 0)
#define PDS_VALUE_FIELD_PWM (1ul << 1)
#define PDS_VALUE_FIELD_STATE (1ul << 2)
#define PDS_VALUE_FIELD_LOADS (1ul << 3)
#define PDS_VALUE_FIELD_FAULTS (1ul << 4)
#define PDS_VALUE_FIELD_MPPT (1ul << 5)
#define PDS_VALUE_FIELD_INPUTS (1ul << 6)
#define PDS_VALUE_FIELD_COMMANDS (1ul << 7)
#define PDS_VALUE_FIELD_ALL 0xFFFFFFFFul

#define PDS_REQUESTED_MODE_OFF 0u
#define PDS_REQUESTED_MODE_FLIGHT 1u
#define PDS_REQUESTED_MODE_MPPT_TEST 2u
#define PDS_REQUESTED_MODE_STATE_TEST 3u
#define PDS_REQUESTED_MODE_FIXED_PWM_TEST 4u

#define EPS_PCU_MODE_MPPT_CHARGE 0u
#define EPS_PCU_MODE_CV_FLOAT 1u
#define EPS_PCU_MODE_SA_LOAD_FOLLOW 2u
#define EPS_PCU_MODE_BATTERY_DISCHARGE 3u

#define EPS_SATELLITE_MODE_MEASUREMENT 0u
#define EPS_SATELLITE_MODE_CHARGING 1u
#define EPS_SATELLITE_MODE_UHF_COMMUNICATION 2u
#define EPS_SATELLITE_MODE_SAFE 3u

#define EPS_SAFE_SUB_STATE_DETUMBLING 0u
#define EPS_SAFE_SUB_STATE_CHARGING 1u
#define EPS_SAFE_SUB_STATE_COMMUNICATION 2u
#define EPS_SAFE_SUB_STATE_REBOOT 3u

#define CHIPS_STATUS_SUCCESS 0u
#define CHIPS_STATUS_UNKNOWN_COMMAND 1u
#define CHIPS_STATUS_INVALID_PAYLOAD_LENGTH 2u
#define CHIPS_STATUS_PARAMETER_OUT_OF_RANGE 3u
#define CHIPS_STATUS_COMMAND_NOT_AVAILABLE 4u

#endif
